######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 17 08:14:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CSVtoDBConverter.h
SOURCES += CSVtoDBConverter.cpp main.cpp
