######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 12 03:07:10 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += DBBuilder.h
SOURCES += DBBuilder.cpp main.cpp
