; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	c:\Users\matt6809\documents\visual studio 2010\Projects\assembly\assembly\assembly.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
EXTRN	__imp____iob_func:PROC
EXTRN	__imp__fprintf:PROC
$SG-5	DB	'%s', 0aH, 00H
PUBLIC	_main
_TEXT	SEGMENT
_i$ = -4						; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC						; COMDAT
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN3@main
$LN2@main:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN3@main:
	mov	ecx, DWORD PTR _i$[ebp]
	cmp	ecx, DWORD PTR _argc$[ebp]
	jge	SHORT $LN1@main
	mov	edx, DWORD PTR _i$[ebp]
	mov	eax, DWORD PTR _argv$[ebp]
	mov	ecx, DWORD PTR [eax+edx*4]
	push	ecx
	push	OFFSET $SG-5
	call	DWORD PTR __imp____iob_func
	add	eax, 32					; 00000020H
	push	eax
	call	DWORD PTR __imp__fprintf
	add	esp, 12					; 0000000cH
	jmp	SHORT $LN2@main
$LN1@main:
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
